# Generated by Django 5.0.1 on 2025-10-29 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancealert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='complianceevidence',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='complianceframework',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='compliancereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dataretentionpolicy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='securityscan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='compliancealert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='compliancealert',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancealert',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='compliancealert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='compliancecontrol',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='complianceframework',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
