# Generated by Django 5.0.1 on 2025-10-03 04:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SSLCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("auto_renew", models.BooleanField(default=True)),
                ("last_renewal_attempt", models.DateTimeField(blank=True, null=True)),
                ("renewal_failed_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expiring_soon", "Expiring Soon"),
                            ("expired", "Expired"),
                            ("renewal_failed", "Renewal Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "SSL Certificate",
                "verbose_name_plural": "SSL Certificates",
                "db_table": "core_ssl_certificate",
            },
        ),
        migrations.CreateModel(
            name="SystemHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cpu_percent", models.FloatField()),
                ("memory_percent", models.FloatField()),
                ("memory_used_mb", models.IntegerField()),
                ("memory_total_mb", models.IntegerField()),
                ("disk_percent", models.FloatField()),
                ("disk_used_gb", models.FloatField()),
                ("disk_total_gb", models.FloatField()),
                ("active_deployments", models.IntegerField()),
                ("failed_deployments", models.IntegerField()),
                ("is_healthy", models.BooleanField(default=True)),
                ("issues", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "System Health Check",
                "verbose_name_plural": "System Health Checks",
                "db_table": "core_system_health_check",
            },
        ),
        migrations.CreateModel(
            name="GitHubConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_user_id", models.IntegerField(unique=True)),
                ("username", models.CharField(max_length=100)),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(blank=True, max_length=255)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Connection",
                "verbose_name_plural": "GitHub Connections",
                "db_table": "core_github_connection",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", models.CharField(max_length=32, unique=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("backup_codes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "2FA Setting",
                "verbose_name_plural": "2FA Settings",
                "db_table": "core_two_factor_auth",
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("password_change", "Password Changed"),
                            ("2fa_enabled", "2FA Enabled"),
                            ("2fa_disabled", "2FA Disabled"),
                            ("2fa_success", "2FA Success"),
                            ("2fa_failed", "2FA Failed"),
                            ("token_created", "API Token Created"),
                            ("token_revoked", "API Token Revoked"),
                            ("deployment_created", "Deployment Created"),
                            ("deployment_deleted", "Deployment Deleted"),
                            ("database_accessed", "Database Credentials Accessed"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("unauthorized_access", "Unauthorized Access Attempt"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Audit Log",
                "verbose_name_plural": "Security Audit Logs",
                "db_table": "core_security_audit_log",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_securi_created_b91357_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="core_securi_event_t_ffa2cd_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="core_securi_severit_6ed0a6_idx"
                    ),
                ],
            },
        ),
    ]
