# Generated by Django 5.0.1 on 2025-10-19 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='deployments.basedeployment'),
        ),
    ]
