# Generated by Django 5.0.1 on 2025-10-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="WebOps",
                        help_text="Name displayed in browser title and header",
                        max_length=100,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo image (recommended: 200x50px, PNG with transparency)",
                        null=True,
                        upload_to="branding/logos/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon (recommended: 32x32px or 64x64px, PNG/ICO)",
                        null=True,
                        upload_to="branding/favicons/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Primary brand color (hex format: #RRGGBB)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#1e40af",
                        help_text="Secondary brand color (hex format: #RRGGBB)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#10b981",
                        help_text="Accent color for success states (hex format: #RRGGBB)",
                        max_length=7,
                    ),
                ),
                (
                    "header_bg_color",
                    models.CharField(
                        default="#1f2937",
                        help_text="Header background color (hex format: #RRGGBB)",
                        max_length=7,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Branding Settings",
                "verbose_name_plural": "Branding Settings",
                "db_table": "core_branding_settings",
            },
        ),
    ]
