# Generated by Django 5.0.1 on 2025-10-11 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_brandingsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HuggingFaceConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("access_token", models.CharField(max_length=500)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("read", "Read-only"),
                            ("write", "Write"),
                            ("fine-grained", "Fine-grained"),
                        ],
                        default="read",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("last_validation_error", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="huggingface_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hugging Face Connection",
                "verbose_name_plural": "Hugging Face Connections",
                "db_table": "core_huggingface_connection",
            },
        ),
    ]
