# Generated by Django 5.0.1 on 2025-10-11 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_huggingfaceconnection"),
        (
            "deployments",
            "0003_deployment_dtype_deployment_gpu_memory_utilization_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("webhook", "Webhook URL"),
                            ("smtp", "SMTP Email"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Channel configuration (email address, webhook URL, SMTP settings, etc.)",
                    ),
                ),
                ("notify_on_deploy_success", models.BooleanField(default=True)),
                ("notify_on_deploy_failure", models.BooleanField(default=True)),
                ("notify_on_deploy_start", models.BooleanField(default=False)),
                ("notify_on_health_check_fail", models.BooleanField(default=True)),
                ("notify_on_resource_warning", models.BooleanField(default=False)),
                ("last_notification", models.DateTimeField(blank=True, null=True)),
                ("notification_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Channel",
                "verbose_name_plural": "Notification Channels",
                "db_table": "core_notification_channel",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="core.notificationchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "db_table": "core_notification_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("push", "Push to Branch"),
                            ("pull_request", "Pull Request"),
                            ("release", "Release Created"),
                            ("manual", "Manual Trigger"),
                        ],
                        default="push",
                        max_length=20,
                    ),
                ),
                (
                    "branch_filter",
                    models.CharField(
                        blank=True,
                        help_text="Only trigger for specific branch (empty = all branches)",
                        max_length=100,
                    ),
                ),
                ("secret", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="deployments.deployment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "db_table": "core_webhook",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("triggered_by", models.CharField(blank=True, max_length=100)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "db_table": "core_webhook_delivery",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationchannel",
            index=models.Index(
                fields=["user", "-created_at"], name="core_notifi_user_id_f91bca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationchannel",
            index=models.Index(
                fields=["is_active", "status"], name="core_notifi_is_acti_e9e979_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["secret"], name="core_webhoo_secret_94f437_idx"),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["deployment", "-created_at"],
                name="core_webhoo_deploym_55076c_idx",
            ),
        ),
    ]
