# Generated by Django 5.0.1 on 2025-10-23 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_notificationchannel_core_notifi_is_acti_e9e979_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('system', 'System Default'), ('light', 'Light'), ('dark', 'Dark')], default='system', help_text='Preferred theme for the interface', max_length=20)),
                ('animations_enabled', models.BooleanField(default=True, help_text='Enable UI animations and transitions')),
                ('compact_view', models.BooleanField(default=False, help_text='Use compact spacing for UI elements')),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='medium', help_text='Preferred font size for the interface', max_length=20)),
                ('interface_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', help_text='Preferred interface language', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='User timezone for displaying dates and times', max_length=50)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'ISO (2023-12-25)'), ('MM/DD/YYYY', 'US (12/25/2023)'), ('DD/MM/YYYY', 'European (25/12/2023)'), ('DD.MM.YYYY', 'German (25.12.2023)')], default='YYYY-MM-DD', help_text='Preferred date format', max_length=20)),
                ('time_format', models.CharField(choices=[('12h', '12-hour (3:00 PM)'), ('24h', '24-hour (15:00)')], default='24h', help_text='Preferred time format', max_length=10)),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('browser_notifications_enabled', models.BooleanField(default=True, help_text='Receive browser push notifications')),
                ('deployment_notifications', models.BooleanField(default=True, help_text='Notifications for deployment events')),
                ('security_notifications', models.BooleanField(default=True, help_text='Notifications for security events')),
                ('system_notifications', models.BooleanField(default=True, help_text='Notifications for system updates and maintenance')),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', help_text='Frequency of email notifications', max_length=20)),
                ('activity_tracking', models.BooleanField(default=True, help_text='Track user activity for analytics and improvements')),
                ('personalized_recommendations', models.BooleanField(default=True, help_text='Show personalized recommendations based on usage patterns')),
                ('third_party_integrations', models.BooleanField(default=False, help_text='Allow third-party integrations and services')),
                ('analytics_sharing', models.BooleanField(default=False, help_text='Share anonymous usage data for product improvement')),
                ('dashboard_layout', models.CharField(choices=[('grid', 'Grid Layout'), ('list', 'List Layout'), ('compact', 'Compact Layout')], default='grid', help_text='Preferred dashboard layout', max_length=20)),
                ('default_dashboard_tab', models.CharField(choices=[('overview', 'Overview'), ('deployments', 'Deployments'), ('databases', 'Databases'), ('services', 'Services')], default='overview', help_text='Default tab to show on dashboard', max_length=20)),
                ('items_per_page', models.IntegerField(choices=[(10, '10 items'), (20, '20 items'), (50, '50 items'), (100, '100 items')], default=20, help_text='Number of items to display per page in lists')),
                ('session_timeout', models.IntegerField(choices=[(1, '1 hour'), (8, '8 hours'), (24, '24 hours'), (168, '1 week'), (720, '30 days')], default=24, help_text='Session timeout in hours')),
                ('require_2fa_for_sensitive', models.BooleanField(default=False, help_text='Require 2FA for sensitive operations')),
                ('login_notifications', models.BooleanField(default=True, help_text='Receive notifications for new login attempts')),
                ('show_advanced_options', models.BooleanField(default=False, help_text='Show advanced technical options in the interface')),
                ('debug_mode', models.BooleanField(default=False, help_text='Enable debug information and developer tools')),
                ('beta_features', models.BooleanField(default=False, help_text='Enable beta features and experimental functionality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'core_user_preferences',
            },
        ),
    ]
