# Generated by Django 5.0.1 on 2025-10-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notificationchannel_notificationlog_webhook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandingsettings",
            name="color_harmony",
            field=models.CharField(
                choices=[
                    ("monochromatic", "Monochromatic"),
                    ("complementary", "Complementary"),
                    ("triadic", "Triadic"),
                    ("analogous", "Analogous"),
                    ("split_complementary", "Split Complementary"),
                ],
                default="monochromatic",
                help_text="Color harmony scheme for palette generation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="enforce_wcag_aa",
            field=models.BooleanField(
                default=True,
                help_text="Enforce WCAG AA contrast ratios (4.5:1 for normal text)",
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="enforce_wcag_aaa",
            field=models.BooleanField(
                default=False,
                help_text="Enforce WCAG AAA contrast ratios (7:1 for normal text)",
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="generated_palette",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Auto-generated color palette with semantic names and variants",
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="primary_hue",
            field=models.IntegerField(
                default=217, help_text="Primary color hue (0-360 degrees)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="primary_lightness",
            field=models.IntegerField(
                default=60, help_text="Primary color lightness (0-100%)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="primary_saturation",
            field=models.IntegerField(
                default=91, help_text="Primary color saturation (0-100%)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="supports_dark_mode",
            field=models.BooleanField(
                default=True, help_text="Generate dark mode color variants"
            ),
        ),
        migrations.AlterField(
            model_name="brandingsettings",
            name="primary_color",
            field=models.CharField(
                default="#3b82f6",
                help_text="Primary brand color (hex format: #RRGGBB) - auto-generated from HSL",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="brandingsettings",
            name="secondary_color",
            field=models.CharField(
                default="#1e40af",
                help_text="Secondary brand color (hex format: #RRGGBB) - auto-generated",
                max_length=7,
            ),
        ),
    ]
