# Generated by Django 5.0.1 on 2025-10-29 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuration',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='googleconnection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='googleconnection',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googleconnection',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='googleconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='huggingfaceconnection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='huggingfaceconnection',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='huggingfaceconnection',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='huggingfaceconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhook',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AlterField(
            model_name='githubconnection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='googleconnection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='huggingfaceconnection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
