# Generated by Django 5.0.1 on 2025-10-29 03:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brandingsettings_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Notification title/headline', max_length=200)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('notification_type', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='info', help_text='Type of notification (affects icon and color)', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., "deployment", "alert", "database")', max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('action_text', models.CharField(blank=True, default='View', help_text='Text for the action button', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification metadata')),
                ('is_important', models.BooleanField(default=False, help_text='High-priority notification (shown prominently)')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'db_table': 'core_user_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_user_n_user_id_09f189_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='core_user_n_user_id_0f75c8_idx'), models.Index(fields=['notification_type', '-created_at'], name='core_user_n_notific_cfb7f4_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='core_user_n_related_28f9e5_idx')],
            },
        ),
    ]
