# Generated by Django 5.0.1 on 2025-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_brandingsettings_color_harmony_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandingsettings",
            name="theme_preset",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("forest", "Forest Theme"),
                    ("ocean", "Ocean Theme"),
                    ("dark", "Dark Theme"),
                    ("premium", "Premium/High Contrast"),
                ],
                default="custom",
                help_text="Predefined theme preset or custom configuration",
                max_length=20,
            ),
        ),
    ]
