# Generated by Django 5.0.1 on 2025-10-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_theme_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandingsettings",
            name="active_scale",
            field=models.FloatField(
                default=0.98,
                help_text="Scale transform for active/pressed states (0.5-2.0)",
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="animation_duration_fast",
            field=models.IntegerField(
                default=150, help_text="Fast animation duration (ms)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="animation_duration_normal",
            field=models.IntegerField(
                default=200, help_text="Normal animation duration (ms)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="animation_duration_slow",
            field=models.IntegerField(
                default=300, help_text="Slow animation duration (ms)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="animation_easing",
            field=models.CharField(
                choices=[
                    ("linear", "Linear"),
                    ("ease", "Ease"),
                    ("ease-in", "Ease In"),
                    ("ease-out", "Ease Out"),
                    ("ease-in-out", "Ease In Out"),
                    ("cubic-bezier(0.4, 0, 0.2, 1)", "Material Design"),
                    ("cubic-bezier(0.68, -0.55, 0.265, 1.55)", "Bounce"),
                ],
                default="cubic-bezier(0.4, 0, 0.2, 1)",
                help_text="Animation easing function",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="border_radius_large",
            field=models.IntegerField(default=16, help_text="Large border radius (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="border_radius_medium",
            field=models.IntegerField(default=8, help_text="Medium border radius (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="border_radius_small",
            field=models.IntegerField(default=4, help_text="Small border radius (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="button_height_large",
            field=models.IntegerField(default=48, help_text="Large button height (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="button_height_medium",
            field=models.IntegerField(
                default=40, help_text="Medium button height (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="button_height_small",
            field=models.IntegerField(default=32, help_text="Small button height (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="component_spacing_compact",
            field=models.IntegerField(
                default=12, help_text="Compact spacing between components (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="component_spacing_normal",
            field=models.IntegerField(
                default=24, help_text="Normal spacing between components (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="component_spacing_relaxed",
            field=models.IntegerField(
                default=48, help_text="Relaxed spacing between components (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="container_padding_desktop",
            field=models.IntegerField(
                default=24, help_text="Container padding for desktop (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="container_padding_mobile",
            field=models.IntegerField(
                default=16, help_text="Container padding for mobile (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="content_max_width",
            field=models.IntegerField(
                default=1280, help_text="Maximum content width (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="enable_themed_shadows",
            field=models.BooleanField(
                default=True, help_text="Use primary color for accent shadows"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="focus_ring_offset",
            field=models.IntegerField(default=2, help_text="Focus ring offset (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="focus_ring_width",
            field=models.IntegerField(default=2, help_text="Focus ring width (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="font_family_mono",
            field=models.CharField(
                default='"JetBrains Mono", "Fira Code", Consolas, "Liberation Mono", Menlo, Courier, monospace',
                help_text="Monospace font family for code and technical text",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="font_family_primary",
            field=models.CharField(
                default='"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
                help_text="Primary font family for UI text",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="font_size_base",
            field=models.FloatField(
                default=1.0,
                help_text="Base font size multiplier (1.0 = 16px, 1.125 = 18px)",
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="font_weight_bold",
            field=models.IntegerField(
                default=700, help_text="Bold text weight (300-900)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="font_weight_medium",
            field=models.IntegerField(
                default=500, help_text="Medium text weight (300-900)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="font_weight_normal",
            field=models.IntegerField(
                default=400, help_text="Normal text weight (300-900)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="header_height_desktop",
            field=models.IntegerField(
                default=64, help_text="Header height on desktop (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="header_height_mobile",
            field=models.IntegerField(
                default=56, help_text="Header height on mobile (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="hover_opacity",
            field=models.FloatField(
                default=0.8, help_text="Opacity for hover states (0.0-1.0)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="hover_scale",
            field=models.FloatField(
                default=1.02, help_text="Scale transform for hover states (0.5-2.0)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="input_height_large",
            field=models.IntegerField(default=48, help_text="Large input height (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="input_height_medium",
            field=models.IntegerField(default=40, help_text="Medium input height (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="input_height_small",
            field=models.IntegerField(default=32, help_text="Small input height (px)"),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="line_height_normal",
            field=models.FloatField(
                default=1.5, help_text="Normal line height for body text"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="line_height_relaxed",
            field=models.FloatField(
                default=1.625, help_text="Relaxed line height for long-form content"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="line_height_tight",
            field=models.FloatField(
                default=1.25, help_text="Tight line height for headings"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="respect_reduced_motion",
            field=models.BooleanField(
                default=True, help_text="Respect user preference for reduced motion"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="shadow_blur_large",
            field=models.IntegerField(
                default=25, help_text="Large shadow blur amount (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="shadow_blur_medium",
            field=models.IntegerField(
                default=15, help_text="Medium shadow blur amount (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="shadow_blur_small",
            field=models.IntegerField(
                default=6, help_text="Small shadow blur amount (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="shadow_intensity",
            field=models.IntegerField(
                default=10, help_text="Shadow intensity percentage (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="sidebar_width_collapsed",
            field=models.IntegerField(
                default=64, help_text="Collapsed sidebar width (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="sidebar_width_desktop",
            field=models.IntegerField(
                default=256, help_text="Sidebar width on desktop (px)"
            ),
        ),
        migrations.AddField(
            model_name="brandingsettings",
            name="spacing_base_unit",
            field=models.IntegerField(
                default=8,
                help_text="Base spacing unit in pixels (typically 4px or 8px)",
            ),
        ),
    ]
