# Generated by Django 5.0.1 on 2025-10-17 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_googleconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Configuration key (e.g., google_oauth_client_id)', max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='Configuration value (encrypted for sensitive data)')),
                ('config_type', models.CharField(choices=[('oauth', 'OAuth Configuration'), ('integration', 'Integration Settings'), ('system', 'System Settings'), ('notification', 'Notification Settings'), ('security', 'Security Settings')], default='system', help_text='Type of configuration', max_length=20)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this value should be encrypted')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('description', models.TextField(blank=True, help_text='Description of what this configuration does')),
                ('default_value', models.TextField(blank=True, help_text='Default value if not set')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'db_table': 'core_configuration',
                'indexes': [models.Index(fields=['key'], name='core_config_key_5c7444_idx'), models.Index(fields=['config_type', 'is_active'], name='core_config_config__9cf59c_idx')],
            },
        ),
    ]
