# Generated by Django 5.0.1 on 2025-09-29 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("repo_url", models.URLField(max_length=500)),
                ("branch", models.CharField(default="main", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("building", "Building"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[("django", "Django"), ("static", "Static Site")],
                        default="django",
                        max_length=20,
                    ),
                ),
                ("port", models.IntegerField(blank=True, null=True, unique=True)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("env_vars", models.JSONField(blank=True, default=dict)),
                (
                    "deployed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment",
                "verbose_name_plural": "Deployments",
                "db_table": "deployments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="deployments.deployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment Log",
                "verbose_name_plural": "Deployment Logs",
                "db_table": "deployment_logs",
                "ordering": ["created_at"],
            },
        ),
    ]
