# Generated by Django 5.0.1 on 2025-10-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='deployed_by',
        ),
    ]
