# Generated by Django 5.0.1 on 2025-10-11 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheckRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("overall_healthy", models.BooleanField(default=True)),
                ("process_healthy", models.BooleanField(default=True)),
                ("http_healthy", models.BooleanField(default=True)),
                ("resources_healthy", models.BooleanField(default=True)),
                ("disk_healthy", models.BooleanField(default=True)),
                ("cpu_percent", models.FloatField(blank=True, null=True)),
                ("memory_mb", models.FloatField(blank=True, null=True)),
                ("disk_free_gb", models.FloatField(blank=True, null=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                ("results", models.JSONField(default=dict)),
                ("auto_restart_attempted", models.BooleanField(default=False)),
                ("auto_restart_successful", models.BooleanField(blank=True, null=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_check_records",
                        to="deployments.deployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Check Record",
                "verbose_name_plural": "Health Check Records",
                "db_table": "health_check_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "-created_at"],
                        name="health_chec_deploym_17e27d_idx",
                    ),
                    models.Index(
                        fields=["overall_healthy", "-created_at"],
                        name="health_chec_overall_d99548_idx",
                    ),
                ],
            },
        ),
    ]
