# Generated by Django 5.0.1 on 2025-10-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0002_healthcheckrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="dtype",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("float16", "Float16"),
                    ("bfloat16", "BFloat16"),
                    ("float32", "Float32"),
                ],
                default="auto",
                help_text="Model data type",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="gpu_memory_utilization",
            field=models.FloatField(
                default=0.9, help_text="GPU memory utilization (0.0-1.0)"
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="max_model_len",
            field=models.IntegerField(
                blank=True, help_text="Maximum model context length", null=True
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="model_name",
            field=models.CharField(
                blank=True,
                help_text="HuggingFace model ID (e.g., meta-llama/Llama-2-7b-chat-hf)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="quantization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("awq", "AWQ"),
                    ("gptq", "GPTQ"),
                    ("squeezellm", "SqueezeLLM"),
                ],
                help_text="Model quantization method",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="tensor_parallel_size",
            field=models.IntegerField(
                default=1, help_text="Number of GPUs for tensor parallelism"
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("django", "Django"),
                    ("static", "Static Site"),
                    ("llm", "LLM Model (vLLM)"),
                ],
                default="django",
                max_length=20,
            ),
        ),
    ]
