# Generated by Django 5.0.1 on 2025-10-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_remove_deployment_deployed_by'),
        ('services', '0002_alter_alert_deployment_alter_healthcheck_deployment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deployment',
        ),
    ]
