# Generated by Django 5.0.1 on 2025-10-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_delete_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmdeployment',
            name='project_type',
            field=models.CharField(choices=[('llm', 'Large Language Model')], default='llm', max_length=20),
        ),
    ]
