# Generated by Django 5.0.1 on 2025-10-24 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_llmdeployment_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_root', models.CharField(blank=True, default='', help_text='Path to Django project root (where manage.py lives)', max_length=500)),
                ('manage_py_path', models.CharField(blank=True, default='', help_text='Path to manage.py file', max_length=500)),
                ('settings_module', models.CharField(blank=True, default='', help_text="Django settings module (e.g., 'config.settings.production')", max_length=255)),
                ('settings_path', models.CharField(blank=True, default='', help_text='Path to settings file or directory', max_length=500)),
                ('wsgi_module', models.CharField(blank=True, default='', help_text="WSGI module path (e.g., 'config.wsgi:application')", max_length=255)),
                ('asgi_module', models.CharField(blank=True, default='', help_text="ASGI module path (e.g., 'config.asgi:application')", max_length=255)),
                ('requirements_file', models.CharField(blank=True, default='', help_text='Path to requirements file to use', max_length=500)),
                ('is_monorepo', models.BooleanField(default=False, help_text='Project is a monorepo (frontend + backend)')),
                ('has_backend_dir', models.BooleanField(default=False, help_text='Project has a backend directory')),
                ('has_split_settings', models.BooleanField(default=False, help_text='Settings are split into multiple files (base, production, etc.)')),
                ('is_auto_detected', models.BooleanField(default=True, help_text='Configuration was auto-detected (vs user-provided)')),
                ('detection_complete', models.BooleanField(default=False, help_text='Structure detection has been completed')),
                ('user_confirmed', models.BooleanField(default=False, help_text='User has confirmed the configuration')),
                ('detection_data', models.JSONField(blank=True, default=dict, help_text='Full detection data from ProjectStructureDetector')),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', help_text='Target deployment environment', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployment', models.OneToOneField(help_text='Associated deployment', on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='deployments.basedeployment')),
            ],
            options={
                'verbose_name': 'Deployment Configuration',
                'verbose_name_plural': 'Deployment Configurations',
                'db_table': 'deployment_configurations',
            },
        ),
    ]
