# Generated by Django 5.0.1 on 2025-10-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_deploymentconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentconfiguration',
            name='asgi_module',
            field=models.CharField(blank=True, default='', help_text="ASGI module path (e.g., 'config.asgi:application')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deploymentconfiguration',
            name='manage_py_path',
            field=models.CharField(blank=True, default='', help_text='Path to manage.py file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deploymentconfiguration',
            name='project_root',
            field=models.CharField(blank=True, default='', help_text='Path to Django project root (where manage.py lives)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deploymentconfiguration',
            name='requirements_file',
            field=models.CharField(blank=True, default='', help_text='Path to requirements file to use', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deploymentconfiguration',
            name='settings_module',
            field=models.CharField(blank=True, default='', help_text="Django settings module (e.g., 'config.settings.production')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deploymentconfiguration',
            name='settings_path',
            field=models.CharField(blank=True, default='', help_text='Path to settings file or directory', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deploymentconfiguration',
            name='wsgi_module',
            field=models.CharField(blank=True, default='', help_text="WSGI module path (e.g., 'config.wsgi:application')", max_length=255, null=True),
        ),
    ]
