# Generated by Django 5.0.1 on 2025-10-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_make_config_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmdeployment',
            name='backend',
            field=models.CharField(choices=[('vllm', 'vLLM (GPU/CPU - High Performance)'), ('transformers', 'Transformers (CPU-Optimized - Fast Setup)'), ('ollama', 'Ollama (Easy CPU Deployment)'), ('tgi', 'Text Generation Inference (Flexible)')], default='transformers', help_text='LLM serving backend to use', max_length=20),
        ),
    ]
