# Generated by Django 5.0.1 on 2025-10-29 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_add_backend_to_llm_deployment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basedeployment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='basedeployment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basedeployment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='deploymentconfiguration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='deploymentconfiguration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deploymentconfiguration',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='deploymentlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='deploymentlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deploymentlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='healthcheckrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='healthcheckrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthcheckrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AlterField(
            model_name='deploymentconfiguration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
