# Generated by Django 5.0.1 on 2025-11-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0008_basedeployment_deleted_at_basedeployment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeployment',
            name='auto_detected',
            field=models.BooleanField(default=False, help_text='Project type auto-detected'),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='build_command',
            field=models.TextField(blank=True, help_text='Auto-generated build command'),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='detected_framework',
            field=models.CharField(blank=True, help_text='Detected framework (e.g., nextjs, fastapi)', max_length=100),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='detected_version',
            field=models.CharField(blank=True, help_text='Detected language/framework version', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='detection_confidence',
            field=models.FloatField(default=0.0, help_text='Detection confidence score (0-1)'),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='install_command',
            field=models.TextField(blank=True, help_text='Auto-generated install command'),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='package_manager',
            field=models.CharField(blank=True, help_text='Detected package manager (npm, pip, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='start_command',
            field=models.TextField(blank=True, help_text='Auto-generated start command'),
        ),
        migrations.AlterField(
            model_name='applicationdeployment',
            name='project_type',
            field=models.CharField(choices=[('django', 'Django'), ('python', 'Python (FastAPI/Flask)'), ('nodejs', 'Node.js'), ('nextjs', 'Next.js'), ('react', 'React'), ('vue', 'Vue.js'), ('laravel', 'Laravel'), ('wordpress', 'WordPress'), ('php', 'PHP'), ('go', 'Go'), ('rust', 'Rust'), ('ruby', 'Ruby/Rails'), ('static', 'Static Site'), ('docker', 'Docker')], default='django', max_length=20),
        ),
    ]
