# Generated by Django 5.0.1 on 2025-11-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0009_add_auto_detection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdeployment',
            name='project_type',
            field=models.CharField(choices=[('django', 'Django'), ('python', 'Python (FastAPI/Flask)'), ('nodejs', 'Node.js'), ('nextjs', 'Next.js'), ('react', 'React'), ('vue', 'Vue.js'), ('laravel', 'Laravel'), ('wordpress', 'WordPress'), ('php', 'PHP'), ('java', 'Java'), ('spring-boot', 'Spring Boot'), ('dotnet', '.NET/C#'), ('aspnet-core', 'ASP.NET Core'), ('elixir', 'Elixir'), ('phoenix', 'Phoenix'), ('go', 'Go'), ('rust', 'Rust'), ('ruby', 'Ruby/Rails'), ('static', 'Static Site'), ('docker', 'Docker')], default='django', max_length=30),
        ),
    ]
