# Generated by Django 5.0.1 on 2025-11-02 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0010_add_enterprise_framework_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmdeployment',
            name='auto_detected',
            field=models.BooleanField(default=False, help_text='Whether model was auto-detected from HuggingFace Hub'),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='backend_confidence',
            field=models.FloatField(default=0.0, help_text='Confidence in backend recommendation', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='backend_recommendation',
            field=models.CharField(blank=True, help_text='Recommended backend based on model analysis', max_length=50),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='detected_architecture',
            field=models.CharField(blank=True, help_text='Auto-detected model architecture (e.g., LlamaForCausalLM)', max_length=200),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='detected_context_length',
            field=models.IntegerField(blank=True, help_text='Auto-detected maximum context length', null=True),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='detected_model_type',
            field=models.CharField(blank=True, help_text='Auto-detected model type (e.g., llama, gpt, mistral)', max_length=100),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='detected_parameter_count',
            field=models.BigIntegerField(blank=True, help_text='Auto-detected parameter count', null=True),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='detected_task_type',
            field=models.CharField(blank=True, help_text='Auto-detected task type (e.g., text-generation)', max_length=100),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='detection_confidence',
            field=models.FloatField(default=0.0, help_text='Confidence score for auto-detection (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='estimated_memory_required_gb',
            field=models.FloatField(blank=True, help_text='Estimated memory requirement in GB', null=True),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='model_author',
            field=models.CharField(blank=True, help_text='Model author from HuggingFace', max_length=200),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='model_downloads',
            field=models.IntegerField(default=0, help_text='Download count from HuggingFace'),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='model_license',
            field=models.CharField(blank=True, help_text='Model license', max_length=100),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='model_likes',
            field=models.IntegerField(default=0, help_text='Likes count from HuggingFace'),
        ),
        migrations.AddField(
            model_name='llmdeployment',
            name='model_tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags from HuggingFace Hub'),
        ),
    ]
