# Generated by Django 5.0.1 on 2025-10-03 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deployments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                ("status_code", models.IntegerField()),
                ("response_time_ms", models.IntegerField()),
                ("is_healthy", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="deployments.deployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Check",
                "verbose_name_plural": "Health Checks",
                "db_table": "health_checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cpu_percent", models.FloatField()),
                ("memory_percent", models.FloatField()),
                ("memory_used_mb", models.IntegerField()),
                ("memory_total_mb", models.IntegerField()),
                ("disk_percent", models.FloatField()),
                ("disk_used_gb", models.FloatField()),
                ("disk_total_gb", models.FloatField()),
                ("network_sent_mb", models.FloatField(default=0.0)),
                ("network_recv_mb", models.FloatField(default=0.0)),
                ("active_connections", models.IntegerField(default=0)),
                ("load_average_1m", models.FloatField(default=0.0)),
                ("load_average_5m", models.FloatField(default=0.0)),
                ("load_average_15m", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Resource Usage",
                "verbose_name_plural": "Resource Usage",
                "db_table": "resource_usage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="resource_us_created_7cda08_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                            ("starting", "Starting"),
                            ("stopping", "Stopping"),
                        ],
                        default="stopped",
                        max_length=20,
                    ),
                ),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("memory_mb", models.FloatField(default=0.0)),
                ("cpu_percent", models.FloatField(default=0.0)),
                ("uptime_seconds", models.IntegerField(default=0)),
                ("restart_count", models.IntegerField(default=0)),
                ("last_checked", models.DateTimeField(auto_now=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_statuses",
                        to="deployments.deployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Status",
                "verbose_name_plural": "Service Statuses",
                "db_table": "service_status",
                "ordering": ["-last_checked"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("cpu_high", "High CPU Usage"),
                            ("memory_high", "High Memory Usage"),
                            ("disk_high", "High Disk Usage"),
                            ("service_down", "Service Down"),
                            ("deployment_failed", "Deployment Failed"),
                            ("ssl_expiring", "SSL Certificate Expiring"),
                            ("database_error", "Database Error"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="deployments.deployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "db_table": "alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="alerts_created_6327ec_idx"
                    ),
                    models.Index(
                        fields=["is_acknowledged"], name="alerts_is_ackn_a32cbc_idx"
                    ),
                    models.Index(fields=["severity"], name="alerts_severit_362484_idx"),
                ],
            },
        ),
    ]
