# Generated by Django 5.0.1 on 2025-10-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_remove_deployment_deployed_by'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='deployments.basedeployment'),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='deployments.basedeployment'),
        ),
        migrations.AlterField(
            model_name='restartattempt',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restart_attempts', to='deployments.basedeployment'),
        ),
        migrations.AlterField(
            model_name='restartpolicy',
            name='deployment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restart_policy', to='deployments.basedeployment'),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='deployments.basedeployment'),
        ),
        migrations.AlterField(
            model_name='sslconfiguration',
            name='deployment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_config', to='deployments.basedeployment'),
        ),
    ]
