# Generated by Django 5.0.1 on 2025-10-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_add_backend_to_llm_deployment'),
        ('services', '0002_alter_alert_deployment_alter_healthcheck_deployment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='deployment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_status', to='deployments.basedeployment'),
        ),
    ]
