# Generated by Django 5.0.1 on 2025-10-18 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_restart_policy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='restartattempt',
            new_name='restart_att_deploym_0deddf_idx',
            old_name='restart_att_deploym_idx',
        ),
        migrations.AlterField(
            model_name='restartattempt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
