# Generated by Django 5.0.1 on 2025-10-29 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_change_servicestatus_to_onetoone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='resourceusage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='resourceusage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceusage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='restartattempt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='restartattempt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restartattempt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
        migrations.AddField(
            model_name='sslconfiguration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='sslconfiguration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sslconfiguration',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash'),
        ),
    ]
