# Generated by Django 5.0.1 on 2025-11-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_datasourcecredential_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('google_docs', 'Google Docs'), ('google_sheets', 'Google Sheets'), ('webhook', 'Webhook Input'), ('database', 'Database Query'), ('api', 'API Request'), ('file', 'File Input'), ('custom_url', 'Custom URL'), ('llm', 'LLM Processor'), ('transform', 'Data Transform'), ('filter', 'Filter'), ('aggregate', 'Aggregate'), ('split', 'Split'), ('merge', 'Merge'), ('code', 'Custom Code'), ('email', 'Email'), ('webhook_output', 'Webhook Output'), ('database_output', 'Database Write'), ('file_output', 'File Output'), ('slack', 'Slack Message'), ('api_output', 'API Call'), ('notification', 'System Notification'), ('condition', 'Conditional'), ('loop', 'Loop'), ('delay', 'Delay'), ('error_handler', 'Error Handler'), ('agent_task', 'Agent Task'), ('agent_query', 'Agent Query'), ('agent_memory', 'Agent Memory'), ('agent_decision', 'Agent Decision'), ('agent_learning', 'Agent Learning')], max_length=50),
        ),
    ]
