# Generated by Django 5.0.1 on 2025-10-19 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('django_app', models.CharField(blank=True, max_length=255)),
                ('cli_entrypoint', models.CharField(blank=True, max_length=255)),
                ('manifest_path', models.CharField(max_length=500)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('settings_schema', models.JSONField(blank=True, default=dict)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_duration_ms', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
