# Generated by Django 5.0.1 on 2025-10-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addon',
            name='last_duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addon',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
    ]
