# Generated by Django 5.0.1 on 2025-11-02 05:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_addon_deleted_at_addon_deleted_by_addon_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('script_path', models.CharField(max_length=500)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('not_installed', 'Not Installed'), ('installing', 'Installing'), ('installed', 'Installed'), ('configuring', 'Configuring'), ('failed', 'Failed'), ('uninstalling', 'Uninstalling'), ('degraded', 'Degraded')], db_index=True, default='not_installed', max_length=20)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('depends_on', models.JSONField(blank=True, default=list)),
                ('provides', models.JSONField(blank=True, default=list)),
                ('conflicts_with', models.JSONField(blank=True, default=list)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_duration_ms', models.IntegerField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_system_addons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Addon',
                'verbose_name_plural': 'System Addons',
                'db_table': 'system_addons',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AddonExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this item has been moved to trash')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this item was moved to trash', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('install', 'Install'), ('uninstall', 'Uninstall'), ('configure', 'Configure'), ('health_check', 'Health Check'), ('validate', 'Validate'), ('status', 'Status Check')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who moved this item to trash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_executions', to=settings.AUTH_USER_MODEL)),
                ('system_addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='addons.systemaddon')),
            ],
            options={
                'verbose_name': 'Addon Execution',
                'verbose_name_plural': 'Addon Executions',
                'db_table': 'addon_executions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['system_addon', '-started_at'], name='addon_execu_system__551579_idx'), models.Index(fields=['status', '-started_at'], name='addon_execu_status_295261_idx')],
            },
        ),
    ]
