# Generated by Django 5.0.1 on 2025-11-06 05:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("max_members", models.IntegerField(default=5)),
                ("max_teams", models.IntegerField(default=3)),
                ("max_deployments", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource", models.CharField(db_index=True, max_length=100)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("code_name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "permissions",
                "indexes": [
                    models.Index(
                        fields=["resource"], name="permissions_resourc_8c0693_idx"
                    ),
                    models.Index(
                        fields=["code_name"], name="permissions_code_na_950180_idx"
                    ),
                ],
                "unique_together": {("resource", "action")},
            },
        ),
        migrations.CreateModel(
            name="ResourcePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.UUIDField()),
                ("is_granted", models.BooleanField(default=True)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_grants",
                        to="enterprise.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resource_permissions",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "role_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="enterprise.organization",
                    ),
                ),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_org_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="enterprise.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_members",
                        to="enterprise.role",
                    ),
                ),
            ],
            options={
                "db_table": "organization_members",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="enterprise.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="enterprise.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_permissions",
            },
        ),
        migrations.CreateModel(
            name="SSOProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("saml", "SAML 2.0"),
                            ("oauth", "OAuth 2.0"),
                            ("oidc", "OpenID Connect"),
                        ],
                        default="saml",
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(max_length=100)),
                ("saml_entity_id", models.CharField(blank=True, max_length=500)),
                ("saml_sso_url", models.URLField(blank=True)),
                ("saml_slo_url", models.URLField(blank=True)),
                ("saml_x509_cert", models.TextField(blank=True)),
                ("saml_sp_entity_id", models.CharField(blank=True, max_length=500)),
                ("saml_acs_url", models.URLField(blank=True)),
                ("saml_metadata_url", models.URLField(blank=True)),
                ("oauth_client_id", models.CharField(blank=True, max_length=500)),
                ("oauth_client_secret", models.CharField(blank=True, max_length=500)),
                ("oauth_authorization_url", models.URLField(blank=True)),
                ("oauth_token_url", models.URLField(blank=True)),
                ("oauth_userinfo_url", models.URLField(blank=True)),
                (
                    "enable_jit_provisioning",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create user accounts on first SSO login",
                    ),
                ),
                (
                    "default_role_slug",
                    models.CharField(
                        default="member",
                        help_text="Default role for JIT provisioned users",
                        max_length=100,
                    ),
                ),
                (
                    "attr_map_email",
                    models.CharField(
                        default="email",
                        help_text="SAML attribute for email",
                        max_length=100,
                    ),
                ),
                (
                    "attr_map_first_name",
                    models.CharField(
                        default="first_name",
                        help_text="SAML attribute for first name",
                        max_length=100,
                    ),
                ),
                (
                    "attr_map_last_name",
                    models.CharField(
                        default="last_name",
                        help_text="SAML attribute for last name",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "force_authn",
                    models.BooleanField(
                        default=False,
                        help_text="Force re-authentication even if user has active session",
                    ),
                ),
                (
                    "sign_requests",
                    models.BooleanField(default=True, help_text="Sign SAML requests"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sso_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_provider",
                        to="enterprise.organization",
                    ),
                ),
            ],
            options={
                "db_table": "sso_providers",
            },
        ),
        migrations.CreateModel(
            name="SSOSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("saml_session_index", models.CharField(blank=True, max_length=500)),
                ("saml_name_id", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("authenticated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("logged_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="enterprise.ssoprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sso_sessions",
                "ordering": ["-authenticated_at"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("max_members", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="enterprise.organization",
                    ),
                ),
            ],
            options={
                "db_table": "teams",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_team_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_members",
                        to="enterprise.role",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="enterprise.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "team_members",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("execute", "Execute"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("permission_change", "Permission Change"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=100)),
                ("resource_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("resource_name", models.CharField(blank=True, max_length=255)),
                (
                    "organization_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("team_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "permissions": [
                    ("view_audit_log", "Can view audit logs"),
                    ("export_audit_log", "Can export audit logs"),
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["organization_id", "timestamp"],
                        name="audit_logs_organiz_9c8c67_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_logs_action_474804_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="organizatio_slug_5b8b37_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="organizatio_is_acti_cad598_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcepermission",
            index=models.Index(
                fields=["user", "resource_type", "resource_id"],
                name="resource_pe_user_id_9344f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcepermission",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="resource_pe_resourc_e05183_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcepermission",
            index=models.Index(
                fields=["expires_at"], name="resource_pe_expires_62daec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["organization", "slug"], name="roles_organiz_796681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["is_system"], name="roles_is_syst_8ea1ed_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["organization", "is_active"],
                name="organizatio_organiz_4b82c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["user", "is_active"], name="organizatio_user_id_fac103_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationmember",
            unique_together={("organization", "user")},
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["role", "permission"], name="role_permis_role_id_29a93b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="ssoprovider",
            index=models.Index(
                fields=["organization", "is_active"],
                name="sso_provide_organiz_8fccd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ssosession",
            index=models.Index(
                fields=["user", "authenticated_at"],
                name="sso_session_user_id_06b0dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ssosession",
            index=models.Index(
                fields=["provider", "authenticated_at"],
                name="sso_session_provide_dc5a53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["organization", "is_active"], name="teams_organiz_055827_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["organization", "slug"], name="teams_organiz_01852c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["team", "is_active"], name="team_member_team_id_1299bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["user", "is_active"], name="team_member_user_id_9ce09b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "user")},
        ),
    ]
