# Generated by Django 5.0.1 on 2025-10-19 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons', '0001_initial'),
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('db_type', models.CharField(choices=[('postgresql', 'Postgresql'), ('mysql', 'Mysql'), ('mongodb', 'Mongodb'), ('sqlite', 'Sqlite'), ('redis', 'Redis'), ('pinecone', 'Pinecone')], default='postgresql', max_length=50)),
                ('host', models.CharField(blank=True, default='localhost', max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('database_name', models.CharField(blank=True, max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('environment', models.CharField(blank=True, max_length=100)),
                ('connection_uri', models.TextField(blank=True)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('connection_timeout', models.IntegerField(default=30)),
                ('pool_size', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='deployments.basedeployment')),
                ('required_addons', models.ManyToManyField(blank=True, help_text='Addons required for this database to function properly', related_name='databases', to='addons.addon')),
            ],
            options={
                'verbose_name': 'Database',
                'verbose_name_plural': 'Databases',
                'db_table': 'databases',
                'ordering': ['-created_at'],
            },
        ),
    ]
