# Generated by Django 5.0.1 on 2025-09-29 22:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deployments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=500)),
                ("host", models.CharField(default="localhost", max_length=255)),
                ("port", models.IntegerField(default=5432)),
                (
                    "deployment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="databases",
                        to="deployments.deployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Database",
                "verbose_name_plural": "Databases",
                "db_table": "databases",
            },
        ),
    ]
